version: '3'
services:
  elasticsearch:
    image: "docker.elastic.co/elasticsearch/elasticsearch:7.1.0"
    environment:
      - bootstrap.memory_lock=true
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
      - cluster.routing.allocation.disk.threshold_enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: 'elasticsearch'
    ports:
      - "9200:9200"
    networks: 
      blog_network:
        ipv4_address: 10.5.0.2
    hostname: elasticsearch
  kibana:
    image: "docker.elastic.co/kibana/kibana:7.1.0"
    depends_on:
      - elasticsearch
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks: 
      blog_network:
        ipv4_address: 10.5.0.3
    hostname: kibana
  blog:
    build: .
    image: blog:0.0.1
    ports: 
      - 8000:8000
    depends_on:
      - elasticsearch
      - kibana
    networks: 
      blog_network:
        ipv4_address: 10.5.0.4
    hostname: blog
    environment:
      - DJANGO_PRODUCTION=true

networks:
  blog_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.5.0.0/16